### PR TITLE
qtwebkit: Add patch to fix build with bison 3.7

### PR DESCRIPTION
**Pull request by schnitzeltony**
Fixes:
|... /build/DerivedSources/WebCore/XPathGrammar.cpp:120:10: fatal error: XPathGrammar.hpp: No such file or directory
|   120 | #include "XPathGrammar.hpp"
|       |          ^~~~~~~~~~~~~~~~~~
| ...
| .../build/DerivedSources/WebCore/CSSGrammar.cpp:160:10: fatal error: CSSGrammar.hpp: No such file or directory
|   160 | #include "CSSGrammar.hpp"
|       |          ^~~~~~~~~~~~~~~~

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
In master-next, thanks

**Comment by shr-project** [comment]
Merged thanks
   23f78f70..b7255751  master -> master
