### PR TITLE
python3-pyqt5: Update to 5.15 version

### PR DESCRIPTION
**Pull request by kraj**
5.13 release no longer works with QT 5.15+ since it uses some of removed
interfaces

Fixes
QtQuick/sipQtQuickQSGGeometry.cpp:940:103: error: use of deleted function 'QSGGeometry& QSGGeometry::operator=(const QSGGeometry&)'

Signed-off-by: Khem Raj <raj.khem@gmail.com>

### CODE REVIEW

**Comment by shr-project** [comment]
in master-next now, thanks

**Comment by shr-project** [comment]
```
ERROR: python3-pyqt5-+5.15.1.dev2006161728-r0 do_fetch: Fetcher failure for URL: 'https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5-5.15.1.dev2006161728.tar.gz'. Checksum mismatch!
File: '/OE/build/oe-core/downloads/PyQt5-5.15.1.dev2006161728.tar.gz' has sha256 checksum b29e4771be495018faef9687919395165da49d391c840c4d1a2592c1089ce592 when 52a9c11724920a34eed288ae2fd8a97adf603c29adcfc6a41ba48962ea493653 was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[sha256sum] = "b29e4771be495018faef9687919395165da49d391c840c4d1a2592c1089ce592"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.
ERROR: python3-pyqt5-+5.15.1.dev2006161728-r0 do_fetch: Fetcher failure for URL: 'https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5-5.15.1.dev2006161728.tar.gz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /OE/build/oe-core/tmp-glibc/work/core2-64-oe-linux/python3-pyqt5/+5.15.1.dev2006161728-r0/temp/log.do_fetch.1105381
```

**Comment by kraj** [comment]
interesting, after `bitbake -ccleanall` I could reproduce it. so I wonder if upstream changed the tarballs, since it has been building file on my systems for few days now.
